services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Username=postgres;Password=postgres;Database=stockdb"
      Jwt__Key: ${JWT_KEY}
    ports:
      - "8080:8080"

volumes:
  pgdata: