name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore StockSolution.sln

      - name: Build
        run: dotnet build StockSolution.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test StockSolution.sln --no-build --verbosity normal
